### ISSUE TITLE
1.8.1 build fails on Linux (Swift 5.1.3)

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-snapshot-testing#367]
Just FYI - I'll try bumping my swift version up to 5.2 to see if that helps but after updating to 1.8.1 (from 1.7.1) my linux build started failing with the following errors:

```
swift test --parallel --enable-code-coverage
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Combine.framework/Modules/Combine.swiftmodule/x86_64-apple-macos.swiftinterface:648:1: error: unknown attribute '_hasMissingDesignatedInitializers'
@_hasMissingDesignatedInitializers @available(iOS 13.0, OSX 10.15, tvOS 13.0, watchOS 6.0, *)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/SwiftUI.framework/Modules/SwiftUI.swiftmodule/x86_64-apple-macos.swiftinterface:5:8: error: failed to load module 'Combine'
import Combine
       ^
/Users/sas/Downloads/Rester/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/Snapshotting/SwiftUIView.swift:1:5: error: failed to load module 'SwiftUI'
#if canImport(SwiftUI)
    ^
...
```

**Comment by finestructure** [comment]
Bumping the base image up to 5.2.4 fixes it :)

**Comment by stephencelis** [comment]
Good to know! Thanks, Sven!
