### ISSUE TITLE
Build failure with Swift 6.3 open-source toolchain

### ISSUE THREAD

**Issue by gohanlon** [pointfreeco/swift-snapshot-testing#1085]
**Describe the bug**

swift-snapshot-testing fails to build with the open-source `swift-6.3-RELEASE` toolchain. Builds fine with Xcode's Swift 6.2.4. I haven't tested Xcode 26.4 (requires macOS 26).

```
AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
```

**To Reproduce**

[Install Swiftly](https://www.swift.org/install/) (swift.org's toolchain manager), then:

```
swiftly install 6.3.0
swiftly use 6.3.0
swift build --build-tests
```

(`swift build` alone succeeds — `canImport(Testing)` is false without `--build-tests`.)

**Environment**

- swift-snapshot-testing: main (ad5e319)
- Xcode 26.3.0 (Swift 6.2.4 — builds fine)
- Swift: `swift-6.3-RELEASE` toolchain from swift.org
- OS: macOS 15.7.5 (arm64)

**Additional context**

`Data: Attachable` and `NSImage: AttachableAsImage` live in cross-import overlay modules (`_Testing_Foundation`, `_Testing_AppKit`). SwiftPM only passes `-enable-cross-import-overlays` to test targets ([source](https://github.com/swiftlang/swift-package-manager/blob/dda772607e25f062942f4537b125a2a4edd4f5dc/Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift#L1150)), so the `SnapshotTesting` library target can't see them.

The failure only manifests on Apple platforms because the `Attachment.record` calls are inside `#if !os(Android) && !os(Linux) && !os(Windows)` guards — though those guards may be unnecessary for the Swift Testing path, since `Attachment` is cross-platform unlike the `XCTContext`/`XCTAttachment` APIs they were originally protecting.

**Comment by gohanlon** [comment]
I might have a simple fix for this. `Array<UInt8>: Attachable` is in the main `Testing` module (not in an overlay), so:

```diff
 import Foundation
 import XCTest

-#if canImport(UIKit)
-  import UIKit
-#elseif canImport(AppKit)
-  import AppKit
-#endif
-
 #if canImport(Testing)
   import Testing
 #endif
```

```diff
 #if canImport(Testing) && compiler(>=6.2)
   private func recordSwiftTestingAttachment(
     _ data: Data,
     named name: String,
     sourceLocation: SourceLocation
   ) {
     #if !os(Android) && !os(Linux) && !os(Windows)
-      #if compiler(>=6.3) && (canImport(UIKit) || canImport(AppKit))
-        if #available(iOS 14.0, tvOS 14.0, macOS 11.0, *),
-          name.hasSuffix(".png"),
-          let image = Image(data: data)
-        {
-          Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
-          return
-        }
-      #endif
-      Attachment.record(data, named: name, sourceLocation: sourceLocation)
+      Attachment.record(Array(data), named: name, sourceLocation: sourceLocation)
     #endif
   }
 #endif
```

Builds and tests pass on both Swift 6.2.4 and 6.3.0. I verified that `Attachment.record(Array(data), named:)` works correctly (byte fidelity, PNG image attachments, etc.). The following script can be used to reproduce that verification:

<details>
<summary>Verification script (creates a standalone test package, runnable via <code>swift test</code> or in Xcode)</summary>

```bash
mkdir -p /tmp/AttachmentVerification/Tests/AttachmentVerificationTests

cat > /tmp/AttachmentVerification/Package.swift << 'EOF'
// swift-tools-version: 6.0
import PackageDescription
let package = Package(
  name: "AttachmentVerification",
  platforms: [.macOS(.v13), .iOS(.v16), .tvOS(.v16)],
  targets: [
    .testTarget(name: "AttachmentVerificationTests")
  ]
)
EOF

cat > /tmp/AttachmentVerification/Tests/AttachmentVerificationTests/AttachmentVerificationTests.swift << 'SWIFT'
import Foundation
import Testing

#if canImport(AppKit)
  import AppKit
#endif
#if canImport(UIKit)
  import UIKit
#endif

@Suite("Attachment.record with Array(data)")
struct AttachmentVerificationTests {
  @Test("Array(data) preserves bytes exactly")
  func arrayFromDataPreservesBytes() {
    let original: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]
    #expect(Array(Data(original)) == original)
  }

  @Test("Attachment value is byte-identical to source Data")
  func attachmentValue() {
    let bytes: [UInt8] = [0xFF, 0xD8, 0xFF, 0xE0]
    let attachment = Attachment(Array(Data(bytes)), named: "test.jpg")
    #expect(attachment.attachableValue == bytes)
  }

  @Test("Record text data")
  func recordTextData() {
    Attachment.record(Array(Data("Hello from Array(data)".utf8)), named: "hello.txt")
  }

  @Test("Record empty data")
  func recordEmptyData() {
    Attachment.record(Array(Data()), named: "empty.bin")
  }

  @Test("Record large data (1 MB)")
  func recordLargeData() {
    let data = Data(repeating: 0xAB, count: 1_000_000)
    let attachment = Attachment(Array(data), named: "large.bin")
    #expect(attachment.attachableValue.count == 1_000_000)
    Attachment.record(Array(data), named: "large.bin")
  }

  private static var isAppKit: Bool {
    #if canImport(AppKit)
      true
    #else
      false
    #endif
  }

  private static var isUIKit: Bool {
    #if canImport(UIKit) && !os(watchOS)
      true
    #else
      false
    #endif
  }

  @Test("Record PNG via AppKit",
    .enabled(if: isAppKit, "AppKit not available on this platform"))
  func recordPNGViaAppKit() throws {
    #if canImport(AppKit)
      let image = NSImage(size: NSSize(width: 100, height: 100), flipped: false) { rect in
        NSColor.red.setFill()
        rect.fill()
        return true
      }
      let cgImage = try #require(image.cgImage(forProposedRect: nil, context: nil, hints: nil))
      let pngData = try #require(
        NSBitmapImageRep(cgImage: cgImage).representation(using: .png, properties: [:])
      )
      Attachment.record(Array(pngData), named: "red-square.png")
    #endif
  }

  @Test("Record PNG via UIKit",
    .enabled(if: isUIKit, "UIKit not available on this platform"))
  func recordPNGViaUIKit() throws {
    #if canImport(UIKit) && !os(watchOS)
      let pngData = UIGraphicsImageRenderer(size: CGSize(width: 100, height: 100)).pngData {
        UIColor.red.setFill()
        $0.fill(CGRect(x: 0, y: 0, width: 100, height: 100))
      }
      Attachment.record(Array(pngData), named: "red-square.png")
    #endif
  }
}
SWIFT

cd /tmp/AttachmentVerification
for v in 6.2.4 6.3.0; do
  echo "=== Swift $v ==="
  swiftly use "$v"
  swift package clean
  swift test 2>&1 \
    | grep -E "passed|failed|skipped|error:"
done
```

</details>

**Comment by Heckscheibe** [comment]
our app also runs into this build failure when we are building for WatchOS, which is not covered by the `if #available` statements, also SwiftUI is not covered by the `canImport` statements. 
For us this fix is quite essentials, because it is now blocking us from using the most recent version.

**Comment by mbrandonw** [comment]
> (`swift build` alone succeeds — `canImport(Testing)` is false without `--build-tests`.)

Hi @gohanlon, can you explain why it is you need to be able to build this library's tests using Swiftly? It seems that we are really the only ones that need to be able to build tests (as well as our CI).

> our app also runs into this build failure when we are building for WatchOS, which is not covered by the `if #available` statements, also SwiftUI is not covered by the `canImport` statements. For us this fix is quite essentials, because it is now blocking us from using the most recent version.

Hi @Heckscheibe, this seems unrelated to this issue. In general you should not be building this library in any test target that runs watchOS tests since the library does not support watchOS. If you want to discuss more I recommend opening a dedicated [discussion](https://github.com/pointfreeco/swift-snapshot-testing/discussions) instead of continuing in this issue.

**Comment by gohanlon** [comment]
@mbrandonw I hit this building my own project that depends on swift-snapshot-testing, not building this library's tests directly. I'm using the open-source `swift-6.3-RELEASE` toolchain because I'm on macOS 15 and can't run Xcode 26.4. (More broadly, my workflow is SwiftPM without Xcode for macOS and server-side work.) When my project runs `swift test`, SwiftPM builds the `SnapshotTesting` library target as a dependency, and the cross-import overlay issue surfaces there.

I used `swift build --build-tests` on this repo in the issue as the simplest way to reproduce it in isolation. Here's a downstream repro that fails with `swift test` on Swift 6.3:

```bash
mkdir -p /tmp/downstream-repro/Sources/MyLib /tmp/downstream-repro/Tests/MyLibTests

cat > /tmp/downstream-repro/Package.swift << 'EOF'
// swift-tools-version: 6.0
import PackageDescription
let package = Package(
  name: "DownstreamRepro",
  platforms: [.macOS(.v13)],
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", branch: "main")
  ],
  targets: [
    .target(name: "MyLib"),
    .testTarget(name: "MyLibTests", dependencies: [
      "MyLib",
      .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
    ])
  ]
)
EOF

cat > /tmp/downstream-repro/Sources/MyLib/MyLib.swift << 'EOF'
public struct MyLib {}
EOF

cat > /tmp/downstream-repro/Tests/MyLibTests/MyLibTests.swift << 'EOF'
import Testing
import SnapshotTesting

@Test func example() {
  assertSnapshot(of: "hello", as: .dump)
}
EOF

cd /tmp/downstream-repro
swiftly use 6.3.0
swift test
```

**Comment by tomwyr** [comment]
I also observe a similar issue when trying to run tests using Swift 6.3 with swift-macro-testing. So far, I've been able to work around the error by decreasing swift-snapshot-testing's version (before Swift Testing Attachments support):
```swift
dependencies: [
  .package(url: "https://github.com/swiftlang/swift-syntax.git", from: "602.0.0"),
  .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", exact: "1.18.9"),
]
```

Output from a failed library build:
<details>
<summary>swift test</summary>

```
Building for debugging...
/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |           `- error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
649 |           return
650 |         }

Testing.Attachment:1:15: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
2 |     public var preferredName: String { get }
3 | }

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'T' = 'NSImage'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'T' = 'NSImage'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
650 |         }
651 |       #endif
652 |       Attachment.record(data, named: name, sourceLocation: sourceLocation)
    |       `- error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
653 |     #endif
654 |   }

Testing.Attachment:1:15: note: where 'AttachableValue' = 'Data'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = 'Data'
2 |     public var preferredName: String { get }
3 | }
/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |           `- error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
649 |           return
650 |         }

Testing.Attachment:1:15: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
2 |     public var preferredName: String { get }
3 | }

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'T' = 'NSImage'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'T' = 'NSImage'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
650 |         }
651 |       #endif
652 |       Attachment.record(data, named: name, sourceLocation: sourceLocation)
    |       `- error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
653 |     #endif
654 |   }

Testing.Attachment:1:15: note: where 'AttachableValue' = 'Data'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = 'Data'
2 |     public var preferredName: String { get }
3 | }
/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |           `- error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
649 |           return
650 |         }

Testing.Attachment:1:15: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
2 |     public var preferredName: String { get }
3 | }

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'T' = 'NSImage'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'T' = 'NSImage'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
650 |         }
651 |       #endif
652 |       Attachment.record(data, named: name, sourceLocation: sourceLocation)
    |       `- error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
653 |     #endif
654 |   }

Testing.Attachment:1:15: note: where 'AttachableValue' = 'Data'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = 'Data'
2 |     public var preferredName: String { get }
3 | }
/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |           `- error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
649 |           return
650 |         }

Testing.Attachment:1:15: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
2 |     public var preferredName: String { get }
3 | }

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'T' = 'NSImage'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'T' = 'NSImage'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
650 |         }
651 |       #endif
652 |       Attachment.record(data, named: name, sourceLocation: sourceLocation)
    |       `- error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
653 |     #endif
654 |   }

Testing.Attachment:1:15: note: where 'AttachableValue' = 'Data'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = 'Data'
2 |     public var preferredName: String { get }
3 | }
/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:11: error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |           `- error: generic struct 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
649 |           return
650 |         }

Testing.Attachment:1:15: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
2 |     public var preferredName: String { get }
3 | }

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that '_AttachableImageWrapper<NSImage>' conform to 'AttachableWrapper'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'AttachableValue' = '_AttachableImageWrapper<NSImage>'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:648:22: error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
646 |           let image = Image(data: data)
647 |         {
648 |           Attachment.record(image, named: name, as: .png, sourceLocation: sourceLocation)
    |                      `- error: static method 'record(_:named:as:sourceLocation:)' requires that 'NSImage' conform to 'AttachableAsImage'
649 |           return
650 |         }

Testing.Attachment.record:2:20: note: where 'T' = 'NSImage'
1 | generic struct Attachment {
2 | public static func record<T>(_ image: T, named preferredName: String? = nil, as imageFormat: AttachableImageFormat? = nil, sourceLocation: SourceLocation = #_sourceLocation) where AttachableValue : _AttachableImageWrapper<T>, AttachableValue : AttachableWrapper, T : AttachableAsImage}
  |                    `- note: where 'T' = 'NSImage'
3 | 

/Users/tomwyr/dev/projects/swift-macro-attachable/.build/checkouts/swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:652:7: error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
650 |         }
651 |       #endif
652 |       Attachment.record(data, named: name, sourceLocation: sourceLocation)
    |       `- error: generic struct 'Attachment' requires that 'Data' conform to 'Attachable'
653 |     #endif
654 |   }

Testing.Attachment:1:15: note: where 'AttachableValue' = 'Data'
1 | public struct Attachment<AttachableValue> where AttachableValue : Attachable, AttachableValue : ~Copyable {
  |               `- note: where 'AttachableValue' = 'Data'
2 |     public var preferredName: String { get }
3 | }
[379/381] Compiling SnapshotTesting URLRequest.swift
error: fatalError
```

</details>

**Comment by dpolishchuk1212** [comment]
Confirming this also reproduces on **Xcode 26.5 (Swift 6.4)** — the original report wasn't sure about Xcode 26.x. Same errors:

```
AssertSnapshot.swift:648: 'Attachment' requires that '_AttachableImageWrapper<NSImage>' conform to 'Attachable'
AssertSnapshot.swift:652: 'Attachment' requires that 'Data' conform to 'Attachable'
```

Consistent with the cross-import-overlay analysis: `swift build` is fine, it only fails once `canImport(Testing)` is true (`--build-tests`, or when a downstream package builds `SnapshotTesting` as a test dependency).

For anyone landing here: the `fix-swiftly` branch (which uses `Attachment.record([UInt8](data), …)`, i.e. @gohanlon's `Array<UInt8>: Attachable` approach) **does compile `--build-tests` on Swift 6.4**. But PRs #1090 and #1113 are both closed, and `fix-swiftly` is now behind the `1.19.6` release, so there's currently no released or mergeable fix for people on Xcode 26.x / Swift 6.4.

As a stopgap, applying that one-line change on top of `1.19.6` (via a `revision:` pin to a fork) unblocks the build. Also worth noting @Heckscheibe's point above: the image path's `#if compiler(>=6.3) && (canImport(UIKit) || canImport(AppKit))` / `#available` guards miss watchOS and SwiftUI, so those configurations need covering too.

Would a minimal PR against `main` — just the `Array(data)` change for the data path, plus widening the guards — be welcome? Happy to open one if it helps get this released.
